name: Publish package to GitHub Packages
on:
  release:
    type: published
jobs:
  publish:
    runs-on: ubuntu-18.04
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          path: go/src/github.com/${{ github.repository }}
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: goto repos
        run: cd ~/.m2/repository
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.JAVA_TOKEN }}
